language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
env:
  global:
    - PINS="mirage-crypto:. mirage-crypto-rng:. mirage-crypto-pk:."
    - PACKAGE="mirage-crypto-pk"
    - TESTS=true
matrix:
  include:
  - os: osx
    env: OCAML_VERSION=4.08
  - dist: xenial
    env: OCAML_VERSION=4.08
notifications:
  email: false
